version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: chatbot-backend
    restart: always
    ports:
      - "8000:8000"  # Expose FastAPI service for Nginx reverse proxy
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - chatbot_net

  frontend:
    build:
      context: ./frontend
    container_name: chatbot-frontend
    restart: always
    ports:
      - "3000:3000"  # Expose Next.js frontend for Nginx reverse proxy
    networks:
      - chatbot_net

networks:
  chatbot_net:
    driver: bridge
